//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliningWpf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IvanovEntities : DbContext
    {
        public IvanovEntities()
            : base("name=IvanovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City> City { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Requests> Requests { get; set; }
        public DbSet<Schedules> Schedules { get; set; }
        public DbSet<Service_Request> Service_Request { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
