//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliningWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.Service_Request = new HashSet<Service_Request>();
        }
    
        public int RequestID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<int> EquipmentID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ICollection<Service_Request> Service_Request { get; set; }
    }
}
