//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliningWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Request
    {
        public int ServiceID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Requests Requests { get; set; }
    }
}
